# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on:
  push:
    branches:
      - '[0-9]**'
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '.gitignore'
    tags-ignore:
      - '[0-9]+.[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '.github/**'
      - '.gitignore'
jobs:
  build:
    uses: StrikerRockers-Mods/.github/.github/workflows/build.yml@main